import os
from pathlib import Path
import json
from pprint import pprint
import argparse


def list_video_names(videos_path, video_list_file):
    """
    Creates a file containing the list of all the video names (no suffix) for the videos in 'video_path'
    """
    with open(video_list_file, 'w') as f:
        p = Path(videos_path)
        for videoCategory in [child for child in p.iterdir() if child.is_dir()]:
            for videoNumber in [vNum for vNum in videoCategory.iterdir() if vNum.is_dir()]:
                f.write(videoCategory.stem + "/" + videoNumber.stem + "\n")


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='OpenPose to ST-GCN JSON format converter.')
    # folder that contains all the video that have been treated by OpenPose
    parser.add_argument('--videos_path', default='/store/ucf_sports/ucf_sports_actions/ucf action/')
    # folder that contains all the JSON files generated by OpenPose (for all the frames of all the videos)
    parser.add_argument('--openpose_json_path', default='data/ucf_sports/poses/openpose_format')
    # folder that will contain the converted files (one per video)
    parser.add_argument('--stgcn_json_path', default='data/ucf_sports/poses/st-gcn_format')
    # file that will contain the list of all the video file names that were treated by OpenPose
    parser.add_argument('--video_list_file', default='data/ucf_sports/data_list.dat')
    # file that will contain the labels for each video
    parser.add_argument('--labels_file', default='data/ucf_sports/poses/fake_labels.json')

    arg = parser.parse_args()

    list_video_names(arg.videos_path, arg.video_list_file)

    p = Path(arg.videos_path)

    if not os.path.exists(arg.stgcn_json_path):
        os.mkdir(arg.stgcn_json_path)

    labels = {}
    label_key_index_mapping = {}
    with open(arg.video_list_file, 'r') as f:
        for line in f:
            video_name = line.strip('\n')
            arg.stgcn_data_array = []
            stgcn_data = {}
            dest_path = os.path.join(arg.stgcn_json_path, video_name.replace("/", ".") + '.json')
            print(video_name)
            for i, path in enumerate(sorted(p.glob(video_name + '/openpose/*.json'))):  # each json file for this video
                json_path = str(path)
                # frame_id = int(path.stem.split('_')[1])
                frame_id = i
                frame_data = {'frame_index': frame_id}
                data = json.load(open(json_path))
                skeletons = []
                for person in data['people']:
                    score, coordinates = [], []
                    skeleton = {}
                    keypoints = person['pose_keypoints_2d']
                    for i in range(0, len(keypoints), 3):
                        coordinates += [keypoints[i], keypoints[i + 1]]
                        score += [keypoints[i + 2]]
                    skeleton['pose'] = coordinates
                    skeleton['score'] = score
                    skeletons += [skeleton]
                frame_data['skeleton'] = skeletons
                arg.stgcn_data_array += [frame_data]

            video_category = video_name.split("/")[0]

            if video_category not in label_key_index_mapping:
                label_key_index_mapping[video_category] = len(label_key_index_mapping)

            labels[video_name] = {"has_skeleton": True,
                                  "label": video_category,
                                  "label_index": label_key_index_mapping[video_category]}

            stgcn_data['data'] = arg.stgcn_data_array
            stgcn_data['label'] = video_category
            stgcn_data['label_index'] = label_key_index_mapping[video_category]
            with open(dest_path, 'w') as outfile:
                json.dump(stgcn_data, outfile)

    with open(arg.labels_file, 'w') as label_file:
        json.dump(labels, label_file)
